### ISSUE TITLE
Customize the filename when calling download_scan

### ISSUE THREAD

**Issue by nemec** [davea/doxiegrabber#1]
If you delete all scans from the Doxie internal storage and then scan more, the filename numbering will restart at `IMG_0001.JPG`. I'm writing a script that will back up the scanned files to a directory, but I need to find a way to rename the images to something less likely to conflict between backups.

Each entry in `scans.json` contains the modified timestamp, which would work perfectly, but it's not available in the current feature set.

I don't know if format strings in parameters is "good" Python, but it would be nice to be able to do something like this:

```
scanner.download_scans(".", "{modified} - {name}.JPG")
> download to "2016-07-15 00:00:00 - IMG_0001.JPG"
```

**Comment by davea** [comment]
`download_scans` is convenience method for quickly grabbing all the files. If you want to do more complex file handling the best thing to do is to iterate over the `.scans` property which provides the `modified`, `name` and `size` values for each available scan.
In my experience the realtime clock of the Doxie will often reset and the `modified` value should be taken with a pinch of salt. If you need a unique identifier for each downloaded file then the most reliable way I've found is to hash the file content itself.
