### ISSUE TITLE
Project has partial Python 2 support

### ISSUE THREAD

**Issue by Stealthii** [davea/doxiegrabber#4]
There remains some compatibility issues with Python 2 with this project. They can be fixed but this may heed future development (by requiring constant checking for Python 2 incompatible changes).

**Comment by Stealthii** [comment]
This issue can be fixed with either of the following two PRs:

* https://github.com/davea/doxieapi/pull/5 - fix remaining Python 2.7 issues
* https://github.com/davea/doxieapi/pull/6 - drop support for Python < 3.4

As Pythons below 3.4 are no longer supported upstream, and some newer features and changes are more awkward whilst maintaining compatibility, I'd vote for https://github.com/davea/doxieapi/pull/6, allowing other PRs I'm hoping to raise such as  [file timestamp](https://github.com/Stealthii/doxieapi/tree/feature/scan-timestamp) or [session re-work and modern Doxie scanner support](https://github.com/Stealthii/doxieapi/tree/feature/session) to be implemented without major workarounds for Python 2.x.

**Comment by davea** [comment]
Python 3 support gets my support :) Merged #6 accordingly.
